INSERT INTO SEARCH_HISTORY SET ID=1, SEARCH_WORD='조회수테스트', SEARCH_COUNT=1, CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';
INSERT INTO SEARCH_HISTORY SET ID=123123L, SEARCH_WORD='검색어', SEARCH_COUNT=2, CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';
INSERT INTO SEARCH_HISTORY SET ID=123124L, SEARCH_WORD='블로그 검색 기능', SEARCH_COUNT=2, CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';
INSERT INTO SEARCH_HISTORY SET ID=123125L, SEARCH_WORD='라이언', SEARCH_COUNT=3, CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';
INSERT INTO SEARCH_HISTORY SET ID=123126L, SEARCH_WORD='춘식이', SEARCH_COUNT=4, CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';


INSERT INTO BOOKMARK_BLOG SET ID=1, LOGIN_ID='accountC', BOOKMARK_TITLE='황의조', BOOKMARK_URL='https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%ED%99%A9%EC%9D%98%EC%A1%B0&oquery=%EC%86%90%ED%9D%A5%EB%AF%BC&tqi=hXIlrsprvxZssuGuAnossssstxV-413194', CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';
INSERT INTO BOOKMARK_BLOG SET ID=2, LOGIN_ID='accountC', BOOKMARK_TITLE='북마크테스트1', BOOKMARK_URL='북마크 URL2', CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';
INSERT INTO BOOKMARK_BLOG SET ID=3, LOGIN_ID='accountC', BOOKMARK_TITLE='북마크테스트2', BOOKMARK_URL='북마크 URL3', CREATED_AT=NOW(), CREATED_BY='ADMIN', UPDATED_AT=NOW(), UPDATED_BY='ADMIN';
